version: '3.9'

services:
  neo4j:
    image: neo4j:5.17
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - neo4j
    env_file:
      - .env

volumes:
  neo4j_data:
